# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterStatsPlus
                                 A QGIS plugin
 Calculates detailed statistics of a selected raster layer, allows you to choose the band via a menu, and generates histogram and Gaussian curve plots.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-16
        copyright            : (C) 2025 by Dr. Geol. Faustino Cetraro
        email                : geol-faustino@libero.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterStatsPlus class from file RasterStatsPlus.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_stats_plus import RasterStatsPlus
    return RasterStatsPlus(iface)
